### ISSUE TITLE
做的太棒了！完美符合我的预期！

### ISSUE THREAD

**Issue by linchuanXu** [Antonoko/Windrecorder#14]
做的太棒了！完美符合我的预期！把我潜在的需求都挖出来了。

都可以成为一个独立的商业产品了，增加一些创意工坊和插件，直接可以创业开公司卖软件了！

做的真不错，特此来夸一下作者。

其实市面上基于LLM ChatGPT很多都是无中生有的需求，但是这个和人工智能结合起来，完全可以成为一个智能的贴身管家！

**Comment by Antonoko** [comment]
谢谢认可！因为储存的数据库和视频文件都是暴露出来的，怎么使用这些数据、也许大家会有不同想法，做插件平台和 LLM 确实都是挺有趣的方向（比如用一年份的数据做个年度报告啦、统计某些名人/消息在自己的视野中出现过多少次、看看当年今日在做什么、用某一段时间的视频生成延时视频啦之类的。现在能采集到的数据维度还不够多，也是一个需要建设的短板）
