### ISSUE TITLE
Automatic Flexible Screenshots Mode does not work | 自动灵活截图模式无法运行

### ISSUE THREAD

**Issue by RTLiang** [Antonoko/Windrecorder#190]
0.015版本升级到0.0.16版本，自动灵活截图模式无法运行，原因未知。
看了下代码，截下来的图片应该存在`cache_screenshot`里面，但是此处没有图片。也不知道怎么调试，要不出一个调试的教程？
![image](https://github.com/yuka-friends/Windrecorder/assets/54389220/0e9e1f3c-db1e-448e-83d0-c48a1cd119e2)
**ENGLISH TRANSLATION**
I updated to 0.0.16 from 0.0.15, but I have no idea why the Automatic Flexible Screenshots mode does not work.
I think these screenshots are supposed to be in `cache_screenshot` directory, but there is no files. I don't know how to debug, can we get a tutorial about debugging？

**Comment by Antonoko** [comment]
感谢反馈！你可以这样进行手动测试该模块是否起作用：

1. 在根目录下创建 test.py 文件，内容如下：
```python
from windrecorder.record import record_screen_via_screenshot_process

record_screen_via_screenshot_process()
```
2. 在根目录下新建一个名字为`DEBUGMODE.txt`的空文件（测试完毕后请记得删除，以避免过多的日记记录 IO
3. 在根目录下执行以下命令：
    1. poetry shell
    2. python test.py
    这样就单独启动了一段自动灵活截图录制过程，你可以切换几个窗口、进行一些浏览操作，然后在命令行中观察录制过程，并进行反馈。如果运作正常，将会在 cache_screenshot 目录下有新增的截图文件。

**Comment by Antonoko** [comment]
感谢测试与反馈！已修复这个低级错误，请更新后再试试 TvT
