### ISSUE TITLE
可以打包放进无法联网的电脑用吗

### ISSUE THREAD

**Issue by 97859** [Antonoko/Windrecorder#32]
请问
![46e9f01607baa98968c110ccb10c4d2](https://github.com/Antonoko/Windrecorder/assets/150599271/ec67460b-405d-4857-8ffc-1c4294d753e9)
这样怎么办？

另外我想放进我的内网电脑，内网电脑无法联网，请问可以在另一台电脑上安装好，再把文件夹打包传过去使用吗，谢谢。

**Comment by Antonoko** [comment]
感谢反馈！问题已修复，可以更新一下试试看🎢。（由于获取数据库路径文件filter写法有问题所导致）
理论上所依赖的包都在虚拟环境安装好后，是可以打包后移动到别的电脑上无需联网使用的。不过由于虚拟环境的机制、需要对虚拟环境中的目录配置稍作调整。可以参考此文：https://blog.csdn.net/dorlolo/article/details/113929415
