### ISSUE TITLE
执行install_update_setting.bat报错Type error

### ISSUE THREAD

**Issue by zhenghewo** [Antonoko/Windrecorder#42]
![image](https://github.com/Antonoko/Windrecorder/assets/26183888/893ba9d9-c6b2-4764-a6d9-30b27c46f2bd)
后续在db_manager.py的第59行加上这两行，得以解决报错
        if self._db_filename_dict is None:
            self._db_filename_dict = {}

**Comment by Antonoko** [comment]
感谢反馈！已修复~
