### ISSUE TITLE
A: 检查系统中是否添加了目标语言的语言包/输入法 如何确定呢？

### ISSUE THREAD

**Issue by shadowwider** [Antonoko/Windrecorder#9]
A: 检查系统中是否添加了目标语言的语言包/输入法：https://learn.microsoft.com/en-us/uwp/api/windows.media.ocr 这个链接其实只是告诉ocr需要系统有需要的语言 并不是教人怎么安装是吧。所以只要是正常使用中文的电脑 这个条件就肯定满足喽？

**Comment by Antonoko** [comment]
对的，执行``install_update_setting.bat``的设置过程中会自动列出系统已安装支持的OCR语言，只要选择所需对应的就ok啦。如果不存在所需语言的话，可以再根据输入法/语言安装状况排查；正常情况下只要是使用中文的电脑，就会预装有中文OCR所需的语言环境。

**Comment by bxrjmfh** [comment]
> 对的，执行`install_update_setting.bat`的设置过程中会自动排队系统已安装支持的OCR语言，只需选择所需的就ok啦。如果不存在对应所需语言的话，可以再根据输入法/语言安装情况排查；正常情况下只要使用中文的电脑，即可预装中文OCR所需的语言环境。
但我还是认为OCR的效果不佳，不知道是不是全局的缩放比例太小的缘故？
![image](https://github.com/Antonoko/Windrecorder/assets/79852164/86726575-f368-4947-9e4c-9964c00cbd1b)

**Comment by Antonoko** [comment]
> > 对的，执行`install_update_setting.bat`的设置过程中会自动排队系统已安装支持的OCR语言，只需选择所需的就ok啦。如果不存在对应所需语言的话，可以再根据输入法/语言安装情况排查；正常情况下只要使用中文的电脑，即可预装中文OCR所需的语言环境。
> > 但我还是认为OCR的效果不佳，不知道是不是全局的缩放比例太小的缘故？
> > ![image](https://user-images.githubusercontent.com/79852164/280442929-86726575-f368-4947-9e4c-9964c00cbd1b.png)

看上去是的，

一是 Windows 自带的中文 OCR 比较拉跨，识别率并不算优秀（优势是又快又节能）；

二是处理流程上，如果是高度大于 1500 的屏幕会被判定为高分屏，录制后的视频会缩小到一半的大小（比如 3840x2160 的屏幕会以 1920x1080 的规格录制），在此基础上进行的 OCR 对于小字号来说准确率就会更低一些了。

解决方法目前有两个：
1. 在`windrecorder/record.py`中将86、87行的`target_scale_width = int(origin_width/2)`与`target_scale_height = int(origin_height/2)`中的“/2”移除并保存。这样录制与 OCR 的就是完整的分辨率图像，准确性也会提高；缺点是视频文件体积可能会增大一些，可以在`录制与视频存储`选项卡下`原视频保留几天后进行压缩`中，设置更短的压缩时间来在超过一段时间后二次压缩；
2. 勾选`设置`下的`使用中文形近字进行搜索`，虽然识别结果比较拉跨，但通过搜索时顺便匹配相似的形近字，搜索结果可能仍然有较大概率能被命中。

**Comment by bxrjmfh** [comment]
> > > 对的，执行`install_update_setting.bat`的设置过程中会自动排队系统已安装支持的OCR语言，只需选择所需的就ok啦。如果不存在对应所需语言的话，可以再根据输入法/语言安装情况排查；正常情况下只要使用中文的电脑，即可预装中文OCR所需的语言环境。
> > > 但我还是认为OCR的效果不佳，不知道是不是全局的缩放比例太小的缘故？
> > > ![image](https://user-images.githubusercontent.com/79852164/280442929-86726575-f368-4947-9e4c-9964c00cbd1b.png)
> 
> 看上去是的，
> 
> 一是 Windows 自带的中文 OCR 比较拉跨，识别率并不算优秀（优势是又快又节能）；
> 
> 二是处理流程上，如果是高度大于 1500 的屏幕会被判定为高分屏，录制后的视频会缩小到一半的大小（比如 3840x2160 的屏幕会以 1920x1080 的规格录制），在此基础上进行的 OCR 对于小字号来说准确率就会更低一些了。
> 
> 解决方法目前有两个：
> 
> 1. 在`windrecorder/record.py`中将86、87行的`target_scale_width = int(origin_width/2)`与`target_scale_height = int(origin_height/2)`中的“/2”移除并保存。这样录制与 OCR 的就是完整的分辨率图像，准确性也会提高；缺点是视频文件体积可能会增大一些，可以在`录制与视频存储`选项卡下`原视频保留几天后进行压缩`中，设置更短的压缩时间来在超过一段时间后二次压缩；
> 2. 勾选`设置`下的`使用中文形近字进行搜索`，虽然识别结果比较拉跨，但通过搜索时顺便匹配相似的形近字，搜索结果可能仍然有较大概率能被命中。

谢谢您的建议！
